version: '3'

services:
  monitor:
    build: ../
    restart: always
    command: ["/conf/thor.yaml"]
    volumes:
      - ./thor.yaml:/conf/thor.yaml
  jormungandr-1:
    image: adalove/jormungandr:1.2-jormungandr0.8.6
    restart: always
    environment:
      - RUST_BACKTRACE=full
      - GENESIS_BLOCK_HASH=8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
      - NODE_CONFIG_PATH=/conf/node-config.yaml
    ports:
      - "3001:3001"
      - "3101:3101"
    volumes:
      - node-data-1:/data
      - ./node-config-1.yaml:/conf/node-config.yaml
  jormungandr-2:
    image: adalove/jormungandr:1.2-jormungandr0.8.6
    restart: always
    environment:
      - RUST_BACKTRACE=full
      - GENESIS_BLOCK_HASH=8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
      - NODE_CONFIG_PATH=/conf/node-config.yaml
    ports:
      - "3002:3002"
      - "3102:3101"
    volumes:
      - node-data-2:/data
      - ./node-config-2.yaml:/conf/node-config.yaml
  jormungandr-3:
    image: adalove/jormungandr:1.2-jormungandr0.8.6
    restart: always
    environment:
      - RUST_BACKTRACE=full
      - GENESIS_BLOCK_HASH=8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
      - NODE_CONFIG_PATH=/conf/node-config.yaml
    ports:
      - "3003:3003"
      - "3103:3101"
    volumes:
      - node-data-3:/data
      - ./node-config-3.yaml:/conf/node-config.yaml

volumes:
  node-data-1: {}
  node-data-2: {}
  node-data-3: {}
